### ISSUE TITLE
Pipelineparallel not adding in the UI

### ISSUE THREAD

**Issue by pulkit-jain** [DeJoker/pipeline-parallel-comfy#3]
Hi 

I was trying Pipelineparallel , it shown in node selector but after selecting node is not getting added in the UI.

How to use this Pipelineparallel ?

**Comment by DeJoker** [comment]
Hi, current is a different api server.Try to do compatible with UI, not a UI parallel.

**Comment by pulkit-jain** [comment]
sorry not understood, what you meant.
Can you please explain it?

I want to run independent nodes in thread will it be possible from this ?

**Comment by DeJoker** [comment]
@pulkit-jain I will release this features in days.

**Comment by DeJoker** [comment]
@pulkit-jain 
Hi, UI support is ready, try this PR. https://github.com/DeJoker/pipeline-parallel-comfy/pull/4
